name: deploy-logicapp

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: Bicep
    LOGIC_APP_NAME: BicepLogicApp
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dude
    steps:
    - uses: actions/checkout@v2
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r logicapp.zip helloworld Artifacts connections.json host.json
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: Azure/functions-action@v1
      name: 'Run Azure Functions Action' 
      id: fa
      with:
        app-name: ${{ env.LOGIC_APP_NAME }}
        package: 'logicapp.zip' 
    
        
     